### ISSUE TITLE
CMakeLists need update  a variable name CPYY_MODULE_PATH -> CPPYY_MODULE_PATH

### ISSUE THREAD

**Issue by qingfengxia** [jclay/cppyy-knearestneighbors-example#2]
CPYY_MODULE_PATH -> CPPYY_MODULE_PATH

test past Ubuntu 18.04, py3
line 6 -10

execute_process(COMMAND cling-config --cmake OUTPUT_VARIABLE CPPYY_MODULE_PATH OUTPUT_STRIP_TRAILING_WHITESPACE)
# Make sure this is set to something like:
# ~/.local/lib/python2.7/site-packages/cpyy_backend/cmake 
message("CPPYY_MODULE_PATH: " ${CPPYY_MODULE_PATH})
list(INSERT CMAKE_MODULE_PATH 0 ${CPPYY_MODULE_PATH})

**Comment by qingfengxia** [comment]
it is just fixedby Pull request #1

**Comment by jclay** [comment]
Closed by #1
